
import React, { useState, useEffect } from 'react';
import { GoogleGenAI } from "@google/genai";
import { 
  Video, 
  Sparkles, 
  Download, 
  Loader2, 
  AlertCircle, 
  Monitor, 
  Smartphone,
  ExternalLink,
  ShieldCheck,
  Play
} from 'lucide-react';

type AspectRatio = '16:9' | '9:16';

const VideoGenerator: React.FC = () => {
  const [prompt, setPrompt] = useState('');
  const [aspectRatio, setAspectRatio] = useState<AspectRatio>('16:9');
  const [isLoading, setIsLoading] = useState(false);
  const [videoUrl, setVideoUrl] = useState<string | null>(null);
  const [error, setError] = useState<string | null>(null);
  const [hasKey, setHasKey] = useState(false);
  const [loadingStep, setLoadingStep] = useState('');

  useEffect(() => {
    const checkKey = async () => {
      if (window.aistudio?.hasSelectedApiKey) {
        const selected = await window.aistudio.hasSelectedApiKey();
        setHasKey(selected);
      }
    };
    checkKey();
  }, []);

  const handleOpenKeyDialog = async () => {
    if (window.aistudio?.openSelectKey) {
      await window.aistudio.openSelectKey();
      setHasKey(true);
    }
  };

  const generateVideo = async () => {
    if (!prompt.trim()) return;
    
    setIsLoading(true);
    setError(null);
    setVideoUrl(null);
    setLoadingStep('Initializing video engine...');

    try {
      if (!hasKey) {
        await handleOpenKeyDialog();
      }

      const ai = new GoogleGenAI({ apiKey: process.env.API_KEY });
      
      setLoadingStep('Submitting generation request...');
      let operation = await ai.models.generateVideos({
        model: 'veo-3.1-fast-generate-preview',
        prompt: `A professional, cinematic hospital scene: ${prompt}. Clean lighting, high production value, medical setting.`,
        config: {
          numberOfVideos: 1,
          resolution: '1080p',
          aspectRatio: aspectRatio
        }
      });

      setLoadingStep('Video is being generated by Veo (this may take a few minutes)...');
      
      while (!operation.done) {
        await new Promise(resolve => setTimeout(resolve, 10000));
        operation = await ai.operations.getVideosOperation({ operation: operation });
        setLoadingStep('Still processing... Veo is carefully rendering your hospital visualization.');
      }

      const downloadLink = operation.response?.generatedVideos?.[0]?.video?.uri;
      if (downloadLink) {
        setLoadingStep('Finalizing download...');
        const response = await fetch(`${downloadLink}&key=${process.env.API_KEY}`);
        const blob = await response.blob();
        setVideoUrl(URL.createObjectURL(blob));
      } else {
        throw new Error("Video generation failed - no URI returned.");
      }

    } catch (err: any) {
      console.error("Video generation error:", err);
      if (err.message?.includes("Requested entity was not found")) {
        setHasKey(false);
        setError("API Key verification failed. Please select a key from a paid GCP project.");
      } else {
        setError(err.message || "Failed to generate video. Please ensure your API key has billing enabled.");
      }
    } finally {
      setIsLoading(false);
      setLoadingStep('');
    }
  };

  return (
    <div className="max-w-6xl mx-auto px-4 py-12">
      <div className="text-center mb-12">
        <div className="inline-flex items-center space-x-2 bg-blue-50 text-blue-600 px-4 py-2 rounded-full mb-4">
          <Sparkles className="w-4 h-4" />
          <span className="text-sm font-bold uppercase tracking-wider">Cinematic Medical Studio</span>
        </div>
        <h2 className="text-4xl font-bold text-slate-900 mb-4">Veo Video Lab</h2>
        <p className="text-slate-600 max-w-2xl mx-auto text-lg">
          Generate high-fidelity medical walkthroughs and hospital environments using the new Veo 3.1 engine.
        </p>
      </div>

      <div className="grid lg:grid-cols-12 gap-8 items-start">
        <div className="lg:col-span-4 space-y-6">
          <div className="bg-white rounded-3xl p-6 shadow-xl border border-slate-100">
            <div className="space-y-6">
              <div className="space-y-2">
                <label className="text-sm font-bold text-slate-700">Video Description</label>
                <textarea
                  value={prompt}
                  onChange={(e) => setPrompt(e.target.value)}
                  placeholder="e.g., A slow panning shot across a modern, sunlit hospital lobby with patient reception"
                  rows={4}
                  className="w-full bg-slate-50 border border-slate-200 rounded-2xl p-4 text-sm focus:outline-none focus:ring-2 focus:ring-blue-500 transition-all"
                />
              </div>

              <div className="space-y-3">
                <label className="text-sm font-bold text-slate-700">Aspect Ratio</label>
                <div className="grid grid-cols-2 gap-2">
                  <button
                    onClick={() => setAspectRatio('16:9')}
                    className={`py-3 rounded-xl text-sm font-bold flex flex-col items-center justify-center space-y-1 border transition-all ${
                      aspectRatio === '16:9'
                        ? 'bg-blue-600 text-white border-blue-600 shadow-lg'
                        : 'bg-white text-slate-600 border-slate-200 hover:border-blue-400'
                    }`}
                  >
                    <Monitor className="w-4 h-4" />
                    <span>16:9 Landscape</span>
                  </button>
                  <button
                    onClick={() => setAspectRatio('9:16')}
                    className={`py-3 rounded-xl text-sm font-bold flex flex-col items-center justify-center space-y-1 border transition-all ${
                      aspectRatio === '9:16'
                        ? 'bg-blue-600 text-white border-blue-600 shadow-lg'
                        : 'bg-white text-slate-600 border-slate-200 hover:border-blue-400'
                    }`}
                  >
                    <Smartphone className="w-4 h-4" />
                    <span>9:16 Portrait</span>
                  </button>
                </div>
              </div>

              {!hasKey && (
                <div className="p-4 bg-amber-50 rounded-2xl border border-amber-100 space-y-3">
                  <div className="flex items-start space-x-3">
                    <AlertCircle className="w-5 h-5 text-amber-600 shrink-0 mt-0.5" />
                    <p className="text-[11px] text-amber-700 leading-tight">
                      Veo video generation requires a <strong>paid API key</strong> from a GCP project. Free tier keys are not supported.
                    </p>
                  </div>
                  <button
                    onClick={handleOpenKeyDialog}
                    className="w-full py-2 bg-amber-100 text-amber-800 rounded-lg text-xs font-bold hover:bg-amber-200 transition-colors flex items-center justify-center space-x-2"
                  >
                    <ExternalLink className="w-3 h-3" />
                    <span>Select Paid Project Key</span>
                  </button>
                  <a 
                    href="https://ai.google.dev/gemini-api/docs/billing" 
                    target="_blank" 
                    rel="noopener noreferrer"
                    className="block text-center text-[10px] text-amber-600 underline font-medium"
                  >
                    View Billing Docs
                  </a>
                </div>
              )}

              {hasKey && (
                <div className="flex items-center space-x-2 p-3 bg-green-50 border border-green-100 rounded-xl">
                  <ShieldCheck className="w-4 h-4 text-green-600" />
                  <span className="text-[10px] font-bold text-green-700 uppercase tracking-widest">VEO ENGINE READY</span>
                </div>
              )}

              <button
                disabled={isLoading || !prompt.trim()}
                onClick={generateVideo}
                className="w-full bg-blue-600 text-white font-bold py-4 rounded-2xl hover:bg-blue-700 transition-all shadow-xl shadow-blue-500/20 disabled:opacity-50 flex items-center justify-center space-x-3 group"
              >
                {isLoading ? (
                  <>
                    <Loader2 className="w-5 h-5 animate-spin" />
                    <span>Processing...</span>
                  </>
                ) : (
                  <>
                    <Play className="w-5 h-5 group-hover:scale-110 transition-transform" />
                    <span>Generate Video</span>
                  </>
                )}
              </button>
            </div>
          </div>
          
          {error && (
            <div className="bg-red-50 text-red-600 p-4 rounded-2xl text-xs font-medium border border-red-100 flex items-start space-x-2">
              <AlertCircle className="w-4 h-4 shrink-0" />
              <span>{error}</span>
            </div>
          )}
        </div>

        <div className="lg:col-span-8">
          <div className={`bg-slate-100 rounded-[32px] relative overflow-hidden border-4 border-white shadow-2xl flex items-center justify-center ${aspectRatio === '16:9' ? 'aspect-video' : 'aspect-[9/16] max-h-[800px] mx-auto w-auto'}`}>
            {isLoading ? (
              <div className="p-8 text-center flex flex-col items-center">
                <div className="w-20 h-20 bg-blue-100 rounded-full flex items-center justify-center mb-6 animate-pulse">
                  <Video className="w-10 h-10 text-blue-600" />
                </div>
                <h4 className="text-lg font-bold text-slate-800 mb-2">Generating Vision</h4>
                <p className="text-sm text-slate-500 max-w-sm">{loadingStep}</p>
                <div className="mt-6 w-48 h-1.5 bg-slate-200 rounded-full overflow-hidden">
                  <div className="h-full bg-blue-600 animate-progress origin-left" />
                </div>
              </div>
            ) : videoUrl ? (
              <div className="w-full h-full group">
                <video
                  src={videoUrl}
                  controls
                  autoPlay
                  loop
                  className="w-full h-full object-cover"
                />
                <div className="absolute top-6 right-6 opacity-0 group-hover:opacity-100 transition-opacity">
                  <a
                    href={videoUrl}
                    download={`girm-med-vid-${Date.now()}.mp4`}
                    className="bg-white p-3 rounded-xl shadow-xl hover:bg-slate-50 transition-all text-slate-800 flex items-center space-x-2 font-bold text-xs"
                  >
                    <Download className="w-4 h-4" />
                    <span>Download MP4</span>
                  </a>
                </div>
              </div>
            ) : (
              <div className="text-center p-12">
                <div className="w-24 h-24 bg-white rounded-full flex items-center justify-center mx-auto mb-6 shadow-sm">
                  <Video className="w-12 h-12 text-slate-200" />
                </div>
                <h3 className="text-xl font-bold text-slate-400">Video Canvas</h3>
                <p className="text-slate-400 text-sm max-w-xs mt-2 mx-auto">
                  Bring your medical concepts to life. Describe a scene and let Veo 3.1 create a cinematic loop.
                </p>
              </div>
            )}
          </div>
        </div>
      </div>
      
      <style>{`
        @keyframes progress {
          0% { transform: scaleX(0); }
          50% { transform: scaleX(0.7); }
          100% { transform: scaleX(1); }
        }
        .animate-progress {
          animation: progress 60s cubic-bezier(0.4, 0, 0.2, 1) infinite;
        }
      `}</style>
    </div>
  );
};

export default VideoGenerator;
